.PHONY: clean All

All:
	@echo "----------Building project:[ MCL_practice - Debug ]----------"
	@cd "MCL_practice" && "$(MAKE)" -f  "MCL_practice.mk"
clean:
	@echo "----------Cleaning project:[ MCL_practice - Debug ]----------"
	@cd "MCL_practice" && "$(MAKE)" -f  "MCL_practice.mk" clean
